ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    external-dns.alpha.kubernetes.io/hostname: "boobsrate.com"
  hosts:
    - host: boobsrate.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              port:
                number: 8000
  tls:
    - secretName: tls-titsfrontend-prod
      hosts:
        - boobsrate.com