image:
  env:
    - name: BACKEND_URL
      value: "https://dev.boobsrate.ru"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    external-dns.alpha.kubernetes.io/hostname: "dev.boobsrate.ru"
  hosts:
    - host: dev.boobsrate.ru
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              port:
                number: 8000
  tls:
    - secretName: tls-titsfrontend-dev
      hosts:
        - dev.boobsrate.ru
